# テンプレートリポジトリ用
# このテンプレートを使用してリポジトリを作成した時に削除すること
name: AutoUpdater

on:
  schedule:
    - cron: '* 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: discordjs-japan/actions-ncu@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
